version: "3.7"
services:
  frontend:
    build:
      context: services/frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      main:
    depends_on:
      - api-gateway
    environment:
      API_BASE_URL: api-gateway
    ports:
      - 3000:3000

  api-gateway:
    image: nzweb/cloud305-gateway
    build:
      context: services/api-gateway/
      dockerfile: Dockerfile
    environment:
      MS_PORT: 8000
      AUTH_MS_URL: auth:3003
      PRODUCT_MS_URL: product:3001
    depends_on:
      - product
      - auth
    volumes:
      - ./certs/:/certs/
    networks:
      main:
    ports:
      - 8000:8000

  product:
    image: nzweb/cloud305-product
    build:
      context: services/product-ms/
      dockerfile: Dockerfile
    environment:
      MS_PORT: 3001
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: test
      DB_NAME: example
      DB_PORT: 3306
    depends_on:
      - mysql
    networks:
      main:

  auth:
    image: nzweb/cloud305-auth
    build:
      context: services/auth-ms/
      dockerfile: Dockerfile
    environment:
      MS_PORT: 3003
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: test
      DB_NAME: example
      DB_PORT: 3306
      JWT_SECRET_KEY: secret
    depends_on:
      - mysql
    networks:
      main:

  mysql:
    image: mariadb
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_TCP_PORT=3306
    expose:
      - 3306
    networks:
      main:

  mysql-phpmyadmin:
    image: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: test
      PMA_ARBITRARY: 2
    restart: always
    ports:
      - 8002:80
    depends_on:
      - mysql
    networks:
      main:


  proxy:
    build: proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - product
      - auth
    volumes:
      - ./certs/:/certs/
    networks:
      main:

volumes:
  mysql-data:
networks:
  main:
    driver: bridge
